### ISSUE TITLE
Unable to build android apk after updating to v5.0.0

### ISSUE THREAD

**Issue by pratikbaid3** [mogol/flutter_secure_storage#333]
```
/Users/pratikbaid/Developer/flutter/bin/flutter --no-color build apk

💪 Building with sound null safety 💪

Running Gradle task 'assembleRelease'...                        
/Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-5.0.0/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java:250: error: lambda expressions are not supported in -source 7
            handler.post(() -> methodResult.success(result));
                            ^
  (use -source 8 or higher to enable lambda expressions)
/Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-5.0.0/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java:260: error: method references are not supported in -source 7
            handler.post(methodResult::notImplemented);
                                       ^
  (use -source 8 or higher to enable method references)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_secure_storage:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Running Gradle task 'assembleRelease'...                           37.0s
Gradle task assembleRelease failed with exit code 1
```

**Comment by alex-sandri** [comment]
Duplicate of #330
