### ISSUE TITLE
v5.0.0: error: lambda expressions and method references are not supported in -source 7 (use -source 8 or higher to enable)

### ISSUE THREAD

**Issue by davejlin** [mogol/flutter_secure_storage#330]
I encountered a compiler error when trying to build with ```flutter_secure_storage v5.0.0```.
I was able to fix by adding ```compileOptions``` to specify Java v8 compatibility to your ```build.gradle```:

### Version:

```
flutter_secure_storage: ^5.0.0
```

### Compile error:

```
/Users/user/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-5.0.0/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java:250: error: lambda expressions are not supported in -source 7
            handler.post(() -> methodResult.success(result));
                            ^
  (use -source 8 or higher to enable lambda expressions)
/Users/user/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-5.0.0/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java:260: error: method references are not supported in -source 7
            handler.post(methodResult::notImplemented);
                                       ^
  (use -source 8 or higher to enable method references)
2 errors

FAILURE: Build failed with an exception.
```

### Fix:

I was able to get past the compiler errors by specifying the following ```compileOptions``` in the ```android``` block in:

```.../.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-5.0.0/android/build.gradle```

```
android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 18
        targetSdkVersion 31
        versionCode 6
        versionName "3.3.1"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}
``` 

### flutter doctor -v
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/user/Documents/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Nexus 5X (mobile) • 0256574f4c681f87 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

**Comment by ggirotto** [comment]
I'm facing the same problem

**Comment by juliansteenbakker** [comment]
Thanks for reporting, i have added your suggested fix and will release it asap.

**Comment by juliansteenbakker** [comment]
> I'm facing the same problem. I couldn't fix it using `compileOptions`.

Can you try adding the compileOptions to your own project, and see if that works?

**Comment by davejlin** [comment]
> > I'm facing the same problem. I couldn't fix it using `compileOptions`.
> 
> Can you try adding the compileOptions to your own project, and see if that works?

@juliansteenbakker Thanks ...
I tried that first, but it didn't work (got the same compiler error).  
Only when I added it to yours did it compile successfully.

**Comment by ggirotto** [comment]
> @juliansteenbakker Thanks ... I tried that first, but it didn't work (got the same compiler error). Only when I added it to yours did it compile successfully.

Thanks for the clarification. I'll be waiting for the release @juliansteenbakker

**Comment by nezoat** [comment]
If you're using a very old Gradle version, it will need to be updated.  

In this file: 
android/gradle/wrapper/gradle-wrapper.properties

Update this line:
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip

Then build, should be fixed.

**Comment by RobertHeim** [comment]
@nezoat's this does not work for us

In file `android/gradle/wrapper/gradle-wrapper.properties` changing
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```
to 
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
```
and then running
```
flutter clean
flutter pub get
cd android
./gradlew clean
cd ..
flutter run
```
we still see the original error

**Comment by nezoat** [comment]
In this case, you already had gradle 6, so your issue is something else, but to support Java 8/Lambda features, you need to have Android Gradle Plugin 3.0.0+, and to have that plugin version, you need Gradle 4.1+.    To use Gradle 7+, you need to be using JDK 11+.   

More info here:
https://developer.android.com/studio/write/java8-support
https://developer.android.com/studio/releases/gradle-plugin#updating-plugin

**Comment by juliansteenbakker** [comment]
The fix is to add the following to your own app project:
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by nezoat** [comment]
Adding the compileOptions did not fix it for me, my issue what the Gradle 3 version I was using, which doesn't support Java 8/Lambda.

**Comment by RedsAnDev** [comment]
> The fix is to add the following to your own app project:
> 
> ```
> compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> ```

I'm totally disagree with this solution.  Even use minSDK as 26 in defaultConfig, the issue remains.


```
[✓] Flutter (Channel stable, 2.5.3, on Pop!_OS 21.04 5.13.0-7620-generic, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/andy/Environments/Flutter/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/andy/Environments/Android/SDK/
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /home/andy/.local/share/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-s
      tudio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at
      /home/andy/.local/share/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-s
      tudio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir =
      /home/andy/.local/share/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-s
      tudio/
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.0.0 (API 26)
      (emulator)

! Doctor found issues in 1 category.
```

**Comment by juliansteenbakker** [comment]
I have searched on several places on the internet and all point to the same solution. You also need to upgrade your gradle android plugin to a minimum of 3.0.0 according to this answer: https://stackoverflow.com/a/51229919

Please refer to the official documentation for more explanation: https://developer.android.com/studio/write/java8-support

**Comment by jiangxiaoqiang** [comment]
I am facing the same problem but none of the suggestion would fix it.

**Comment by flutter-clutter** [comment]
I have tried every suggestion in this issue. Nothing fixes the problem for me. No gradle update to latest version, no `compileOptions`.

Only solution for me: using version 4.2.1 of `flutter_secure_storage` instead.

**Comment by Cupidon277** [comment]
Hello guys, I had the same issue and following this thread I fixed it doing the following:

Disclaimer: I started learning Flutter literally two days ago, don't judge if I misused any of the steps below.

Long story short for the experts here, upgrade Gradle to 7+

Below is what I did to solve it

First I ran the `./gradlew --version` command in the android directory of my project and got the following information:

`-------------------------------------------------------------------
Gradle 6.4
-------------------------------------------------------------------
Kotlin: 1.5.31
Groovey: 3.0.9
JVM: 11.0.11 `

Then as juliansteenbakker mentioned I followed the provided link 

https://developer.android.com/studio/releases/gradle-plugin#updating-plugin

And:
1-  Installed gradle 7 by changing the gradle version to `gradle-7.3-all.zip` in the file `android/gradle/wrapper/graddle-wrapper.properties`
2- (I am not sure this helps but I have done it anyways?)
From terminal project root, ran the command `flutter upgrade-packages` then `flutter clean` then `flutter pub get`
3 - Changed the Gradle version in dependencies in the `android/build.gradle`  file as mentioned in the previous link like this:
`class path 'com.android.tools.build:gradle:7.0.0'`
4- From terminal changed directory to android and ran the command `./gradlew clean`


Then i ran again the command `./gradlew --version` from the `android` directory and got the output:

`-------------------------------------------------------
Gradle 7.3
-------------------------------------------------------
.
.
.`

**Comment by mohammedX6** [comment]
@Cupidon277  confirmed this is working. Also, JDK11 or above must be installed to upgrade to Gradle 7

**Comment by juliansteenbakker** [comment]
I have tried the following:
1. Created a whole new app using Android studio new project wizard.
2. Add flutter v5.0.0
3. Get warning message about min sdk being 16 but it should be 18 so i upgrade,
4. Get warning about lambda expressions. 
5. I add the compileOptions to flutter_secure_storage
6. It builds without error.

So i have added the compile options and publish version 5.0.1

I have tried the same as above with version 5.0.1 and i didn't get any warning anymore. So please try version 5.0.1 and report if it works or not.

**Comment by flutter-clutter** [comment]
@juliansteenbakker 
5.0.2 works for me. Thank you for the quick reaction! :)

**Comment by davejlin** [comment]
@juliansteenbakker Thanks much ... yes,  confirming that the latest version 5.0.2 builds find for me now.  Closing issue.

**Comment by k00na** [comment]
Had the same error, after some trial and error, I've managed to fix it by following these steps: 

**File: gradle-wrapper.properties** 
distributionUrl - previously had it set to gradle version 5.4.1., changed it to 7.3 like this: 
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip`

**File: build.gradle** 
Previously had build tools version set to 3.5.4, changed it to 4.2.0 🍀 

```
buildscript {
    ....
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        ....
    }
}
```

Thanks to this, my app now builds successfully. 

Good luck 🤞
